export type LocationCountryOption = {
  id: number;
  name: string;
  iso2: string;
  phone_code: string;
  hasStates: boolean;
};

const RAW_COUNTRIES: Array<Pick<LocationCountryOption, "name" | "iso2" | "phone_code">> = [
  { name: "Afghanistan", iso2: "AF", phone_code: "+93" },
  { name: "Albania", iso2: "AL", phone_code: "+355" },
  { name: "Algeria", iso2: "DZ", phone_code: "+213" },
  { name: "Andorra", iso2: "AD", phone_code: "+376" },
  { name: "Angola", iso2: "AO", phone_code: "+244" },
  { name: "Antigua and Barbuda", iso2: "AG", phone_code: "+1" },
  { name: "Argentina", iso2: "AR", phone_code: "+54" },
  { name: "Armenia", iso2: "AM", phone_code: "+374" },
  { name: "Australia", iso2: "AU", phone_code: "+61" },
  { name: "Austria", iso2: "AT", phone_code: "+43" },
  { name: "Azerbaijan", iso2: "AZ", phone_code: "+994" },
  { name: "Bahamas", iso2: "BS", phone_code: "+1" },
  { name: "Bahrain", iso2: "BH", phone_code: "+973" },
  { name: "Bangladesh", iso2: "BD", phone_code: "+880" },
  { name: "Barbados", iso2: "BB", phone_code: "+1" },
  { name: "Belarus", iso2: "BY", phone_code: "+375" },
  { name: "Belgium", iso2: "BE", phone_code: "+32" },
  { name: "Belize", iso2: "BZ", phone_code: "+501" },
  { name: "Benin", iso2: "BJ", phone_code: "+229" },
  { name: "Bhutan", iso2: "BT", phone_code: "+975" },
  { name: "Bolivia", iso2: "BO", phone_code: "+591" },
  { name: "Bosnia and Herzegovina", iso2: "BA", phone_code: "+387" },
  { name: "Botswana", iso2: "BW", phone_code: "+267" },
  { name: "Brazil", iso2: "BR", phone_code: "+55" },
  { name: "Brunei", iso2: "BN", phone_code: "+673" },
  { name: "Bulgaria", iso2: "BG", phone_code: "+359" },
  { name: "Burkina Faso", iso2: "BF", phone_code: "+226" },
  { name: "Burundi", iso2: "BI", phone_code: "+257" },
  { name: "Cambodia", iso2: "KH", phone_code: "+855" },
  { name: "Cameroon", iso2: "CM", phone_code: "+237" },
  { name: "Canada", iso2: "CA", phone_code: "+1" },
  { name: "Cape Verde", iso2: "CV", phone_code: "+238" },
  { name: "Central African Republic", iso2: "CF", phone_code: "+236" },
  { name: "Chad", iso2: "TD", phone_code: "+235" },
  { name: "Chile", iso2: "CL", phone_code: "+56" },
  { name: "China", iso2: "CN", phone_code: "+86" },
  { name: "Colombia", iso2: "CO", phone_code: "+57" },
  { name: "Comoros", iso2: "KM", phone_code: "+269" },
  { name: "Congo (Brazzaville)", iso2: "CG", phone_code: "+242" },
  { name: "Congo (Kinshasa)", iso2: "CD", phone_code: "+243" },
  { name: "Costa Rica", iso2: "CR", phone_code: "+506" },
  { name: "Croatia", iso2: "HR", phone_code: "+385" },
  { name: "Cuba", iso2: "CU", phone_code: "+53" },
  { name: "Cyprus", iso2: "CY", phone_code: "+357" },
  { name: "Czechia", iso2: "CZ", phone_code: "+420" },
  { name: "Denmark", iso2: "DK", phone_code: "+45" },
  { name: "Djibouti", iso2: "DJ", phone_code: "+253" },
  { name: "Dominica", iso2: "DM", phone_code: "+1" },
  { name: "Dominican Republic", iso2: "DO", phone_code: "+1" },
  { name: "Ecuador", iso2: "EC", phone_code: "+593" },
  { name: "Egypt", iso2: "EG", phone_code: "+20" },
  { name: "El Salvador", iso2: "SV", phone_code: "+503" },
  { name: "Equatorial Guinea", iso2: "GQ", phone_code: "+240" },
  { name: "Eritrea", iso2: "ER", phone_code: "+291" },
  { name: "Estonia", iso2: "EE", phone_code: "+372" },
  { name: "Eswatini", iso2: "SZ", phone_code: "+268" },
  { name: "Ethiopia", iso2: "ET", phone_code: "+251" },
  { name: "Fiji", iso2: "FJ", phone_code: "+679" },
  { name: "Finland", iso2: "FI", phone_code: "+358" },
  { name: "France", iso2: "FR", phone_code: "+33" },
  { name: "Gabon", iso2: "GA", phone_code: "+241" },
  { name: "Gambia", iso2: "GM", phone_code: "+220" },
  { name: "Georgia", iso2: "GE", phone_code: "+995" },
  { name: "Germany", iso2: "DE", phone_code: "+49" },
  { name: "Ghana", iso2: "GH", phone_code: "+233" },
  { name: "Greece", iso2: "GR", phone_code: "+30" },
  { name: "Grenada", iso2: "GD", phone_code: "+1" },
  { name: "Guatemala", iso2: "GT", phone_code: "+502" },
  { name: "Guinea", iso2: "GN", phone_code: "+224" },
  { name: "Guinea-Bissau", iso2: "GW", phone_code: "+245" },
  { name: "Guyana", iso2: "GY", phone_code: "+592" },
  { name: "Haiti", iso2: "HT", phone_code: "+509" },
  { name: "Honduras", iso2: "HN", phone_code: "+504" },
  { name: "Hungary", iso2: "HU", phone_code: "+36" },
  { name: "Iceland", iso2: "IS", phone_code: "+354" },
  { name: "India", iso2: "IN", phone_code: "+91" },
  { name: "Indonesia", iso2: "ID", phone_code: "+62" },
  { name: "Iran", iso2: "IR", phone_code: "+98" },
  { name: "Iraq", iso2: "IQ", phone_code: "+964" },
  { name: "Ireland", iso2: "IE", phone_code: "+353" },
  { name: "Israel", iso2: "IL", phone_code: "+972" },
  { name: "Italy", iso2: "IT", phone_code: "+39" },
  { name: "Ivory Coast", iso2: "CI", phone_code: "+225" },
  { name: "Jamaica", iso2: "JM", phone_code: "+1" },
  { name: "Japan", iso2: "JP", phone_code: "+81" },
  { name: "Jordan", iso2: "JO", phone_code: "+962" },
  { name: "Kazakhstan", iso2: "KZ", phone_code: "+7" },
  { name: "Kenya", iso2: "KE", phone_code: "+254" },
  { name: "Kiribati", iso2: "KI", phone_code: "+686" },
  { name: "Kuwait", iso2: "KW", phone_code: "+965" },
  { name: "Kyrgyzstan", iso2: "KG", phone_code: "+996" },
  { name: "Laos", iso2: "LA", phone_code: "+856" },
  { name: "Latvia", iso2: "LV", phone_code: "+371" },
  { name: "Lebanon", iso2: "LB", phone_code: "+961" },
  { name: "Lesotho", iso2: "LS", phone_code: "+266" },
  { name: "Liberia", iso2: "LR", phone_code: "+231" },
  { name: "Libya", iso2: "LY", phone_code: "+218" },
  { name: "Liechtenstein", iso2: "LI", phone_code: "+423" },
  { name: "Lithuania", iso2: "LT", phone_code: "+370" },
  { name: "Luxembourg", iso2: "LU", phone_code: "+352" },
  { name: "Madagascar", iso2: "MG", phone_code: "+261" },
  { name: "Malawi", iso2: "MW", phone_code: "+265" },
  { name: "Malaysia", iso2: "MY", phone_code: "+60" },
  { name: "Maldives", iso2: "MV", phone_code: "+960" },
  { name: "Mali", iso2: "ML", phone_code: "+223" },
  { name: "Malta", iso2: "MT", phone_code: "+356" },
  { name: "Marshall Islands", iso2: "MH", phone_code: "+692" },
  { name: "Mauritania", iso2: "MR", phone_code: "+222" },
  { name: "Mauritius", iso2: "MU", phone_code: "+230" },
  { name: "Mexico", iso2: "MX", phone_code: "+52" },
  { name: "Micronesia", iso2: "FM", phone_code: "+691" },
  { name: "Moldova", iso2: "MD", phone_code: "+373" },
  { name: "Monaco", iso2: "MC", phone_code: "+377" },
  { name: "Mongolia", iso2: "MN", phone_code: "+976" },
  { name: "Montenegro", iso2: "ME", phone_code: "+382" },
  { name: "Morocco", iso2: "MA", phone_code: "+212" },
  { name: "Mozambique", iso2: "MZ", phone_code: "+258" },
  { name: "Myanmar", iso2: "MM", phone_code: "+95" },
  { name: "Namibia", iso2: "NA", phone_code: "+264" },
  { name: "Nauru", iso2: "NR", phone_code: "+674" },
  { name: "Nepal", iso2: "NP", phone_code: "+977" },
  { name: "Netherlands", iso2: "NL", phone_code: "+31" },
  { name: "New Zealand", iso2: "NZ", phone_code: "+64" },
  { name: "Nicaragua", iso2: "NI", phone_code: "+505" },
  { name: "Niger", iso2: "NE", phone_code: "+227" },
  { name: "Nigeria", iso2: "NG", phone_code: "+234" },
  { name: "North Korea", iso2: "KP", phone_code: "+850" },
  { name: "North Macedonia", iso2: "MK", phone_code: "+389" },
  { name: "Norway", iso2: "NO", phone_code: "+47" },
  { name: "Oman", iso2: "OM", phone_code: "+968" },
  { name: "Pakistan", iso2: "PK", phone_code: "+92" },
  { name: "Palau", iso2: "PW", phone_code: "+680" },
  { name: "Palestine", iso2: "PS", phone_code: "+970" },
  { name: "Panama", iso2: "PA", phone_code: "+507" },
  { name: "Papua New Guinea", iso2: "PG", phone_code: "+675" },
  { name: "Paraguay", iso2: "PY", phone_code: "+595" },
  { name: "Peru", iso2: "PE", phone_code: "+51" },
  { name: "Philippines", iso2: "PH", phone_code: "+63" },
  { name: "Poland", iso2: "PL", phone_code: "+48" },
  { name: "Portugal", iso2: "PT", phone_code: "+351" },
  { name: "Qatar", iso2: "QA", phone_code: "+974" },
  { name: "Romania", iso2: "RO", phone_code: "+40" },
  { name: "Russia", iso2: "RU", phone_code: "+7" },
  { name: "Rwanda", iso2: "RW", phone_code: "+250" },
  { name: "Saint Kitts and Nevis", iso2: "KN", phone_code: "+1" },
  { name: "Saint Lucia", iso2: "LC", phone_code: "+1" },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", phone_code: "+1" },
  { name: "Samoa", iso2: "WS", phone_code: "+685" },
  { name: "San Marino", iso2: "SM", phone_code: "+378" },
  { name: "Sao Tome and Principe", iso2: "ST", phone_code: "+239" },
  { name: "Saudi Arabia", iso2: "SA", phone_code: "+966" },
  { name: "Senegal", iso2: "SN", phone_code: "+221" },
  { name: "Serbia", iso2: "RS", phone_code: "+381" },
  { name: "Seychelles", iso2: "SC", phone_code: "+248" },
  { name: "Sierra Leone", iso2: "SL", phone_code: "+232" },
  { name: "Singapore", iso2: "SG", phone_code: "+65" },
  { name: "Slovakia", iso2: "SK", phone_code: "+421" },
  { name: "Slovenia", iso2: "SI", phone_code: "+386" },
  { name: "Solomon Islands", iso2: "SB", phone_code: "+677" },
  { name: "Somalia", iso2: "SO", phone_code: "+252" },
  { name: "South Africa", iso2: "ZA", phone_code: "+27" },
  { name: "South Korea", iso2: "KR", phone_code: "+82" },
  { name: "South Sudan", iso2: "SS", phone_code: "+211" },
  { name: "Spain", iso2: "ES", phone_code: "+34" },
  { name: "Sri Lanka", iso2: "LK", phone_code: "+94" },
  { name: "Sudan", iso2: "SD", phone_code: "+249" },
  { name: "Suriname", iso2: "SR", phone_code: "+597" },
  { name: "Sweden", iso2: "SE", phone_code: "+46" },
  { name: "Switzerland", iso2: "CH", phone_code: "+41" },
  { name: "Syria", iso2: "SY", phone_code: "+963" },
  { name: "Taiwan", iso2: "TW", phone_code: "+886" },
  { name: "Tajikistan", iso2: "TJ", phone_code: "+992" },
  { name: "Tanzania", iso2: "TZ", phone_code: "+255" },
  { name: "Thailand", iso2: "TH", phone_code: "+66" },
  { name: "Timor-Leste", iso2: "TL", phone_code: "+670" },
  { name: "Togo", iso2: "TG", phone_code: "+228" },
  { name: "Tonga", iso2: "TO", phone_code: "+676" },
  { name: "Trinidad and Tobago", iso2: "TT", phone_code: "+1" },
  { name: "Tunisia", iso2: "TN", phone_code: "+216" },
  { name: "Turkey", iso2: "TR", phone_code: "+90" },
  { name: "Turkmenistan", iso2: "TM", phone_code: "+993" },
  { name: "Tuvalu", iso2: "TV", phone_code: "+688" },
  { name: "Uganda", iso2: "UG", phone_code: "+256" },
  { name: "Ukraine", iso2: "UA", phone_code: "+380" },
  { name: "United Arab Emirates", iso2: "AE", phone_code: "+971" },
  { name: "United Kingdom", iso2: "GB", phone_code: "+44" },
  { name: "United States", iso2: "US", phone_code: "+1" },
  { name: "Uruguay", iso2: "UY", phone_code: "+598" },
  { name: "Uzbekistan", iso2: "UZ", phone_code: "+998" },
  { name: "Vanuatu", iso2: "VU", phone_code: "+678" },
  { name: "Vatican City", iso2: "VA", phone_code: "+379" },
  { name: "Venezuela", iso2: "VE", phone_code: "+58" },
  { name: "Vietnam", iso2: "VN", phone_code: "+84" },
  { name: "Yemen", iso2: "YE", phone_code: "+967" },
  { name: "Zambia", iso2: "ZM", phone_code: "+260" },
  { name: "Zimbabwe", iso2: "ZW", phone_code: "+263" },
];

const COUNTRIES_WITH_STATES = new Set([
  "AU",
  "BR",
  "CA",
  "CN",
  "DE",
  "ES",
  "IN",
  "MX",
  "NG",
  "PK",
  "RU",
  "US",
  "ZA",
]);

export const FALLBACK_COUNTRY_OPTIONS: LocationCountryOption[] = RAW_COUNTRIES.map(
  (country, index) => ({
    id: index + 1,
    name: country.name,
    iso2: country.iso2,
    phone_code: country.phone_code,
    hasStates: COUNTRIES_WITH_STATES.has(country.iso2),
  })
);

export const COUNTRY_CODES = [
  ...new Set(FALLBACK_COUNTRY_OPTIONS.map((country) => country.phone_code))
];
