export const normalizeManagerPermissionName = (name: string): string =>
  (name || "").toString().trim().toLowerCase();

type ModuleFeatureMap = Record<string, string[]>;

export const managerPermissionConfig: Record<string, ModuleFeatureMap> = {
  bonus: {
    bonusList: ["Bonus List"],
    giveBonus: ["Give Bonus"],
    removeBonus: ["Remove Bonus"],
  },
  emailManagement: {
    sendEmail: ["Send Email"],
    getClientEmails: ["Get Client Emails"],
    broadcastEmail: ["Create Broadcast Email", "Broadcast Email"],
    createBroadcastEmail: ["Create Broadcast Email"],
    broadcastEmailHistory: ["Broadcast Email History"],
    manageEmailExclusions: ["Manage Email Exclusions"],
  },
  groupManagement: {
    addGroup: ["Add Group"],
    deleteGroup: ["Delete Group"],
    editGroup: ["Edit Group"],
    groupList: ["Group List"],
    updateMt5Group: ["Update MT5 Group"],
  },
  ibManagement: {
    addCommissionGroup: ["Add Commission Group", "View / Create Commission Group"],
    addIbCommission: ["Add IB Commission"],
    addIbPlan: ["Add IB Plan", "View / Create IB Plan"],
    approveRejectIbRequest: ["Approve/Reject IB Req"],
    commissionGroup: ["Commission Group", "View / Create Commission Group"],
    editCommissionGroup: ["Edit Commission Group", "Edit / Delete Commission Group"],
    editDeleteCommissionGroup: ["Edit / Delete Commission Group"],
    editDeleteIbPlan: ["Edit / Delete IB Plan"],
    editIbCommission: ["Edit IB Commission"],
    ibPlan: ["IB Plan", "View / Create IB Plan"],
    ibRequests: ["IB Requests"],
    ibUsers: ["IB Users"],
    moveClientToIb: ["Move Client to IB"],
    setIbCommission: ["Set IB Commission"],
    viewCommission: ["View Commission"],
    viewCreateCommissionGroup: ["View / Create Commission Group"],
    viewCreateIbPlan: ["View / Create IB Plan"],
    viewLevel: ["View Level", "View Level / Tree chart"],
  },
  newsManagement: {
    addNews: ["Add News"],
    deleteNews: ["Delete News"],
    editNews: ["Edit News"],
    newsList: ["News List"],
  },
  notifications: {
    markAllAsRead: ["Read Notification"],
    markAsRead: ["Read Notification"],
    readNotification: ["Read Notification"],
    unreadNotification: ["Unread Notification"],
    viewNotifications: ["Read Notification", "Unread Notification"],
  },
  reportManagement: {
    allTransactionReport: ["All Transaction Report"],
    commissionReport: ["Partner Commission Report", "Commission Report"],
    dailySummaryReport: ["Daily Summary Report"],
    depositReport: ["Deposit Report"],
    historyReport: ["History Report"],
    ibCommissionReport: [
      "Partner Commission Report",
      "Commission Report",
      "IB Commission Report",
    ],
    ibCommissionWithdrawReport: ["IB Commission Withdraw Report"],
    ibUsersReport: ["Partner Users Report", "IB Users Report"],
    ibWithdrawReport: ["IB Withdraw Report"],
    internalTransferReport: ["Internal Transfer Report"],
    loginActivity: ["Login Activity"],
    lotReport: ["Lot Report"],
    mainWalletHistoryReport: ["Main Wallet History Report"],
    positionReport: ["Position Report"],
    tradingHistoryReport: ["Trading History Report"],
    userReport: ["User Report"],
    walletHistoryReport: ["Wallet History Report"],
    withdrawReport: ["Withdraw Report"],
  },
  "account-types": {
    // "Group Management" in the UI maps to this account-types page (/all-accounts).
    // Account types == groups in this product, and the login response may surface
    // the list permission under either name, so accept both.
    accountTypesList: ["Account Types List", "Group List"],
    createAccountType: ["Create Account Type"],
    editAccountType: ["Edit Account Type"],
    deleteAccountType: ["Delete Account Type"],
  },
  settingsManagement: {
    auditLogs: ["Audit Logs"],
    brokerDepositAccountList: ["Deposit Bank Details", "Broker Deposit Account List"],
    createBrokerDepositAccount: ["Deposit Bank Details", "Create Broker Deposit Account"],
    currencyManagement: ["Currency Management"],
    defaultSetting: ["Default Setting"],
    deleteBrokerDepositAccount: ["Deposit Bank Details", "Delete Broker Deposit Account"],
    depositBankDetails: ["Deposit Bank Details"],
    editBrokerDepositAccount: ["Deposit Bank Details", "Edit Broker Deposit Account"],
    enabledDisabledManager2fa: [
      "Sub-admin 2FA",
      "Enabled/Disabled Subadmin 2FA",
      "Enabled/Disabled Manager 2FA",
    ],
    enabledDisabledSubadmin2fa: ["Sub-admin 2FA", "Enabled/Disabled Subadmin 2FA"],
    enabledDisabledUser2fa: ["User 2FA", "Enabled/Disabled User 2FA"],
    manager2faList: ["Sub-admin 2FA", "Subadmin 2FA List", "Manager 2FA List"],
    subadmin2faList: ["Sub-admin 2FA", "Subadmin 2FA List"],
    promotionList: ["Manager Promotion", "Promotion List"],
    pspSetting: [
      "PSP Setting",
      "Payment Method List",
      "Edit Payment Methods",
      "Delete Payment Methods",
    ],
    user2faList: ["User 2FA", "User 2FA List"],
  },
  ticketManagement: {
    tickets: ["Tickets"],
  },
  transaction: {
    approveDepositList: ["Approve Deposit List", "Deposit List", "Approve/Reject Deposit"],
    approveIbWithdrawalList: ["Approve/Reject IB Withdrawal", "IB Withdrawal List"],
    approveRejectDeposit: ["Approve/Reject Deposit"],
    approveRejectIbWithdrawal: ["Approve/Reject IB Withdrawal"],
    approveRejectWithdrawal: ["Approve/Reject Withdrawal"],
    approveWithdrawalList: ["Approve Withdrawal List", "Withdrawal List", "Approve/Reject Withdrawal"],
    clientDeposit: ["Client Deposit"],
    clientWithdraw: ["Client Withdraw", "Client Withdrawal"],
    depositList: ["Deposit List", "Pending Deposit List", "Approve Deposit List", "Reject Deposit List"],
    ibWithdraw: ["IB Withdraw"],
    ibWithdrawalList: ["IB Withdrawal List"],
    internalTransfer: ["Internal Transfer"],
    pendingDepositList: ["Pending Deposit List", "Deposit List"],
    pendingIbWithdraw: ["Pending IB Withdraw"],
    pendingIbWithdrawalList: ["IB Withdrawal List"],
    pendingWithdraw: ["Pending Withdraw"],
    pendingWithdrawalList: ["Pending Withdraw", "Withdrawal List", "Pending Withdrawal List"],
    rejectDepositList: ["Reject Deposit List", "Deposit List"],
    rejectIbWithdrawalList: ["IB Withdrawal List"],
    rejectWithdrawalList: ["Reject Withdrawal List", "Withdrawal List"],
    walletDeposit: ["Wallet Deposit"],
    walletWithdraw: ["Wallet Withdraw"],
    withdrawalList: ["Withdrawal List", "Pending Withdraw", "Client Withdraw"],
  },
  userManagement: {
    addBankDetails: ["Add Bank Details"],
    addExistingClient: ["Add Existing Client"],
    addUser: ["Add User"],
    approveDocumentsList: [
      "Approve Documents List",
      "Approve Document List",
    ],
    approveRejectKyc: ["Approve/Reject KYC"],
    bankDetailsList: ["Bank Details List"],
    changeMt5Password: ["Change MT5 Password"],
    changeUserPassword: ["Change User Password"],
    createMt5Account: ["Create MT5 Account"],
    deleteBankDetails: ["Delete Bank Details"],
    deleteMt5Account: ["Delete MT5 Account"],
    deleteUser: ["Delete User"],
    editUser: ["Edit User"],
    followUpList: ["Follow Up List"],
    mt5UserList: ["MT5 User List"],
    pendingDocumentsList: ["Pending Documents List", "Pending Document List"],
    rejectDocumentList: ["Reject Document List"],
    resendMt5DataMail: ["Resend MT5 Data Mail"],
    resendVerificationMail: ["Resend Verification Mail"],
    resetGoogle2fa: ["Reset Google 2FA"],
    statusGoogle2fa: ["Status Google 2FA"],
    tempUsersList: ["Temp Users List"],
    updateBankDetails: ["Update Bank Details"],
    updateMt5Leverage: ["Update MT5 Leverage"],
    uploadUserDocuments: ["Upload User Documents"],
    userList: ["User List"],
    userPasswordList: ["User Password List"],
    userSetting: ["User Setting"],
    verifyBankDetails: ["Verify Bank Details"],
    viewUser: ["View User"],
  },
  bonusManagement: {
    bonusList: ["Bonus List"],
    giveBonus: ["Give Bonus"],
    removeBonus: ["Remove Bonus"],
  },
  cryptoWalletManagement: {
    cryptoWalletList: ["Deposit Crypto Details", "Broker Crypto Wallet List", "Crypto Wallet List"],
    addCryptoWallet: ["Deposit Crypto Details", "Create Broker Crypto Wallet", "Add Crypto Wallet"],
    editCryptoWallet: ["Deposit Crypto Details", "Edit Broker Crypto Wallet", "Edit Crypto Wallet"],
    deleteCryptoWallet: ["Deposit Crypto Details", "Delete Broker Crypto Wallet", "Delete Crypto Wallet"],
  },
  subadminManagement: {
    addSubadminPermission: ["Add Subadmin Permission"],
    createSubadmin: ["Create Subadmin"],
    editSubadminPermission: ["Edit Subadmin Permission"],
    subadminList: ["Subadmin List"],
  },
};

export type ManagerPermissionModule = keyof typeof managerPermissionConfig;

export const getManagerPermissionNames = (
  moduleKey: ManagerPermissionModule,
  featureKey: string
): string[] => {
  const moduleConfig = managerPermissionConfig[moduleKey];
  if (!moduleConfig) return [];
  const entry = moduleConfig[featureKey];
  if (!entry) return [];
  return entry.map(normalizeManagerPermissionName);
};
